USE skillsphere_db;

ALTER TABLE users MODIFY password VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE users ADD COLUMN google_id VARCHAR(100) UNIQUE;